### ISSUE TITLE
Missing xenforo_admins_flatfile

### ISSUE THREAD

**Issue by medic917** [Drixevel/Xenforo-Manager#1]
xenforo_admins_flatfile is missing in the scripting folder.

Would love to give it a try if uploaded.

**Comment by oaaron99** [comment]
and the xenforo_admins

**Comment by whtevrwt** [comment]
Yeah...

**Comment by jljr222** [comment]
Let's get that missing file!

**Comment by Drixevel-Archive** [comment]
The module is unfinished, the file will be uploaded once the plugin is done.
